### ISSUE TITLE
Crashes on loading

### ISSUE THREAD

**Issue by ghost** [hicder/PowerTools#12]
On a fresh ChimeraOS install, I get a black screen and the error : 

Something went wrong when displaying this content
Error Reference: Shared SteamUI_845067_XXXX
Cannot read property 'max' of null

Did not have this issue on a previous release.

**Comment by adolfotregosa** [comment]
yeah same for me

**Comment by hicder** [comment]
sorry my bad I never realized there is a bug report. It has been working fine for me on Nobara. Let me install Chimera to debug.

**Comment by hicder** [comment]
ok, v2.5 should fix the crash. Can you try
```
curl -L https://github.com/hicder/PowerTools/releases/latest/download/install.sh | sh
```
