### ISSUE TITLE
Feature request - TDP override (hack)

### ISSUE THREAD

**Issue by matte-schwartz** [hicder/PowerTools#8]
Was playing around with Smokeless umaf to try higher boost on windows and the settings apply to Linux as well. Could adding a tweak to allow a user override of max TDP be possible? Possibly with a warning saying user risk advised beyond 30. 

Technically you can push it to 54W in smokeless but the battery starts discharging past 47W. I have mine set to 45W max in BIOS.

On stock CPU settings, the bios will self-check RyzenAdj and override any TDP over 30W after 5 minutes.

**Comment by fennectech** [comment]
I second this.  However it should be behind a boiler plate warning "we are not responsible if your ally burns your house down or suddenly turns into a Commodore 64 or teaches your cat to open a gate to hell"
